require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ChatApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-simple-toast', :path => '../node_modules/react-native-simple-toast'

  target 'ChatAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ChatApp-tvOS' do
  # Pods for ChatApp-tvOS

  target 'ChatApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
